defaults: &defaults
  _target_: deepbci.data_utils.data_loaders.load_data
  load_method: load_to_memory
  load_method_kwargs:
    subjects: eval(list(range(1, 9+1)))
    trials: eval(list(range(1, 10+1)))
    data_file: eeg.csv
    true_fs: false
    preload_epoch_indexes: 
      generate_sync_epochs: null

groups:
  _target_: deepbci.data_utils.Groups
  data_groups:
    dbci:
    # - <<: *defaults
    #   data_loader: 
    #     _target_: deepbci.data_utils.data_loaders.OAOutLoader

    # - <<: *defaults
    #   data_loader: 
    #     _target_: deepbci.data_utils.data_loaders.OAObsLoader

    - _target_: deepbci.data_utils.data_loaders.load_data
      load_method: load_to_memory
      load_method_kwargs:
        subjects: eval(list(range(10, 11+1))) # Change 10 back to 1
        trials: eval(list(range(1, 5+1))) # Change 5 back to 10
        data_file: eeg.csv
        true_fs: false
        preload_epoch_indexes: 
          generate_sync_epochs: #null # Was null
            use_events: [1] # Used to change only error events, may not work
        # subject_override:
        #   10:
        #     trials: eval(list(range(1, 5+1)))
        #   11:
        #     trials: eval(list(range(1, 5+1)))
      data_loader: 
        _target_: deepbci.data_utils.data_loaders.BGSIntLoader

    # - <<: *defaults
    #   data_loader: 
    #     _target_: deepbci.data_utils.data_loaders.BGSObsLoader

mutate:
- apply_func:
    select: null
    func:
      _partial_: True
      _target_: deepbci.data_utils.mutators.filter
      l_freq: 0.1
      h_freq: 30
      method: iir
      verbose: False
      iir_params:
        order: 4
        ftype: butter
        output: sos

- apply_func:
    select: null
    func:
      _partial_: True
      _target_: deepbci.data_utils.mutators.epoch
      tmin: 0
      tmax: 0.995
      preload: true
      picks: [eeg]
      verbose: WARNING
      baseline: null

- apply_method:
    select: null
    method:
      name: resample
      kwargs: 
        sfreq: 128

- compress:
    compress_level: subject # Compresses all trials



